# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .update_document_by_file_request_data_process_rule import (
    UpdateDocumentByFileRequestDataProcessRule,
)
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class UpdateDocumentByFileRequestData(UniversalBaseModel):
    """
    Document configuration JSON as string
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the document
    """

    indexing_technique: typing.Optional[typing.Literal["high_quality"]] = (
        pydantic.Field(default=None)
    )
    """
    Indexing technique to use
    """

    process_rule: typing.Optional[UpdateDocumentByFileRequestDataProcessRule] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
